[tasks.test_no_std]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features']

[tasks.test_alloc]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features', '--features', 'alloc']

[tasks.test_std]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features', '--features', 'std']

[tasks.test_no_std-nightly]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features', '--features', 'nightly']

[tasks.test_alloc-nightly]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features', '--features', 'alloc,nightly']

[tasks.test_std-nightly]
command = 'cargo'
args = ['test', '--lib', '--tests', '--no-default-features', '--features', 'std,nightly']

[tasks.test_doc]
command = 'cargo'
args = ['test', '--doc', '--all-features']

[tasks.test_all]
dependencies = [
    'test_doc',
    'test_no_std',
    'test_alloc',
    'test_std',
    'test_no_std-nightly',
    'test_alloc-nightly',
    'test_std-nightly',
]

[tasks.check_no_std]
command = 'cargo'
args = ['clippy', '--no-default-features']

[tasks.check_alloc]
command = 'cargo'
args = ['clippy', '--no-default-features', '--features', 'alloc']

[tasks.check_std]
command = 'cargo'
args = ['clippy', '--no-default-features', '--features', 'std']

[tasks.check_no_std-nightly]
command = 'cargo'
args = ['clippy', '--no-default-features', '--features', 'nightly']

[tasks.check_alloc-nightly]
command = 'cargo'
args = ['clippy', '--no-default-features', '--features', 'alloc,nightly']

[tasks.check_std-nightly]
command = 'cargo'
args = ['clippy', '--no-default-features', '--features', 'std,nightly']

[tasks.check_all]
dependencies = [
    'check_no_std-nightly',
    'check_alloc-nightly',
    'check_std-nightly',
    'check_no_std',
    'check_alloc',
    'check_std',
]