max_width = 120
comment_width = 120

blank_lines_upper_bound = 1

fn_single_line = true
format_strings = true

match_arm_leading_pipes = 'Preserve'
merge_imports = true
newline_style = 'Unix'

overflow_delimited_expr = true
trailing_semicolon = false

# group_imports = true